services:
  django:
    env_file:
      - .env
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=lighttraffic_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  pgdbdata: null