# Generated by Django 5.1 on 2024-08-14 11:23

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employer_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0)),
                ('project_name', models.CharField(max_length=100)),
                ('project_discription', models.TextField(max_length=500)),
                ('project_start_time', models.DateTimeField()),
                ('project_end_time', models.DateTimeField()),
                ('employee', models.ManyToManyField(to='projects.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(default=0)),
                ('report_name', models.CharField(max_length=100)),
                ('report_start', models.DateTimeField()),
                ('report_finish', models.DateTimeField()),
                ('report_green_comment', models.TextField(max_length=500)),
                ('report_yellow_comment', models.TextField(max_length=500)),
                ('report_red_comment', models.TextField(max_length=500)),
                ('employee_going_vacation', models.BooleanField(default=False)),
                ('anyone_going_vacation', models.CharField(default='Nobody', max_length=100)),
                ('other_comments', models.TextField(default='Nothing', max_length=1000)),
                ('related_project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.IntegerField(default=0)),
                ('stage_name', models.CharField(max_length=100)),
                ('stage_color', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('Y', 'Yellow')], default='G', max_length=1)),
                ('related_report', models.ForeignKey(default=projects.models.Stages.get_report_id, on_delete=django.db.models.deletion.CASCADE, to='projects.report')),
            ],
        ),
    ]
