# Generated by Django 5.1 on 2024-08-15 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_creater',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.employee'),
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_id', models.IntegerField(default=0)),
                ('objective_name', models.CharField(max_length=100)),
                ('objective_color', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('Y', 'Yellow')], default='G', max_length=1)),
                ('related_report', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.report')),
            ],
        ),
        migrations.DeleteModel(
            name='Stages',
        ),
    ]
